Correctly locate macos python.org built-in tcl/tk
pyinstaller/pyinstaller pull request #5013
Opened 2020-07-20 07:38 UTC by ssantichaivekin

The python.org OS X python distributions installs a built-in version tcl/tk in a path similar to the system installation. This makes pyinstaller confused and think the python.org built-in tcl/tk is the system installation. This pull request fixes this issue. See https://github.com/pyinstaller/pyinstaller/issues/3753#issuecomment-432464838 .

Resolves #3753 .

2020-08-12 11:33 UTC, bwoodsend commented
@ssantichaivekin Sorry for the silence. Thanks for working on this. If this works then it will solve several issues. 

@reritom, @amifunny, could you `pip install https://github.com/ssantichaivekin/pyinstaller/archive/tcl-tk-macos-bugfix.zip` and verify that tkinter works? You can use our go-to hello work tkinter script:

```python
import tkinter
from tkinter import ttk

root = tkinter.Tk()

msg = ttk.Label(root, text='It\'s working just fine.')

msg.grid()

root.mainloop()
```

@nbrummel - This may fix your #5040 too. Could you try it also with your code?

2020-08-12 17:14 UTC, amifunny commented
@bwoodsend Yes, working fine but large amount of warnings are displayed while packing like -
```
2220 WARNING: Several hooks defined for module 'astor'.Please take care they do not conflict.
2220 WARNING: Several hooks defined for module 'astroid'.Please take care they do not conflict.
2225 WARNING: Several hooks defined for module 'astropy'.Please take care they do not conflict.
```
For every global installed package.

2020-08-12 17:42 UTC, ssantichaivekin commented
I used the version with bugfix for my own project and it created a working executable for macOS Catalina 10.15 -- however, the shipped tkinter application executable does not work on my friend's macOS Mojave 10.14. I don't think this is pyinstaller trouble because my friend's macOS Mojave also crashes when running `python -m tkinter` using python from python.org. The problem is documented here: https://stackoverflow.com/questions/57435896/tkinter-crashes-computer-after-macos-10-14-6-update

2020-08-12 19:00 UTC, bwoodsend commented
> I don't think this is pyinstaller trouble 

That's a relief. That issue looks horrible. @ssantichaivekin Can I ask which Python version(s) you've tried this on? There's been some changes somewhere between Python 3.7 and 3.8.5 (I think) which has caused issues. Ideally I'd like this tested on 3.7.0 and whatever the latest 3.8.x currently is.

@amifunny Thanks for testing that. Those warnings are just because you have the hooks repo(s) installed and a PyInstaller from before Legorooj moved the hooks out of there into the hooks repos. It's not relevant to this issue.

2020-08-31 10:15 UTC, bwoodsend commented
@reritom @motatoes Could you both verify this works. Use:
```shell
pip3 install https://github.com/ssantichaivekin/pyinstaller/archive/tcl-tk-macos-bugfix.zip
```

Then try freezing [this hello-world tk example](https://github.com/pyinstaller/pyinstaller/pull/5013#issuecomment-672817826).

2020-08-31 10:22 UTC, rokm approved these changes

2020-08-31 19:43 UTC, bwoodsend commented
@Legorooj does this need a changelog entry? Other than that I think we can consider this tested and ready to merge.

2020-09-01 07:36 UTC, Legorooj requested changes
Looks good! But we need a changelog entry of the `bugfix` category. Please create 2 identical entries with different filenames, one referring to this PR the other to the linked issue. See [here](https://github.com/pyinstaller/pyinstaller/tree/develop/news#readme) for the changelog guide.

2020-09-28 01:30 UTC, merged