hooks: {PyQt5,PySide2}.QtWebEngineWidgets (linux): prevent use of glob if it has no matches
pyinstaller/pyinstaller pull request #5149
Opened 2020-09-07 10:11 UTC by rokm

The glob used to search for extra NSS libraries on linux turns out to have no matches on Fedora 32. 

The `/lib64/nss` directory exists, but contains no libraries, and so adding `/lib64/nss/*.so` to `binaries` results in the following error:

```
Unable to find "/lib64/nss/*.so" when adding binary and data files.
```

2020-09-10 07:42 UTC, htgoebel requested changes
Thanks for this pull-requests. Some remarks:
- I suggest putting the explanation into the commit-message. THis helps understanding the commit without the need to look at the pull-request.
- the commit-messessages's first line is loo long, please restircct ot ca. 70 characters. E.g. you can remove "(linux)" here.
- Please try rephrasing the commit-message. I did not get it when reading, only the after reading the pull-request description. Maybe phrase it like "Fix search for extra NSS libraries"
- Want to add a news-fragment?

2020-09-10 08:21 UTC, rokm commented
Thanks for the feedback! 

I've pushed the update which changes the wording of the commit message as you suggested, and adds the description. 
I also added the news-fragment in a separate commit (assuming the commits will be squashed on merge).

2020-09-14 14:48 UTC, bjones1 approved these changes

2020-10-01 02:13 UTC, Legorooj approved these changes

2020-10-01 02:14 UTC, merged