main: Add informative message what do to if RecurrsionError occurs.
pyinstaller/pyinstaller pull request #5156
Opened 2020-09-10 08:48 UTC by htgoebel

See #4406

2020-09-10 13:24 UTC, bjones1 approved these changes

2020-09-11 00:25 UTC, Legorooj approved these changes
Nice work! EDIT: see below

2020-09-11 00:27 UTC, Legorooj commented
However, the new test fails - can you fix this? Please also fix the lint error as well.

2020-09-11 13:27 UTC, htgoebel commented
Interesting to see the recursion on Python 3.6 is deeper than on he other ones.

2020-09-12 02:06 UTC, Legorooj commented
@htgoebel can you rebase off develop? That should fix the test failures.

2020-09-12 08:31 UTC, htgoebel commented
@Legorooj Will do, but I'm curious: Current develop head only adds "hooks: Stop hooks collecting bytecode files". What is the reason why you expect this to stop the worker-crashes?

2020-09-12 08:36 UTC, Legorooj commented
Current development head also reverts your accidental commit AFAIK - it worked for other PRs with the same issue (I think it's the same issue anyway)

2020-09-13 09:37 UTC, Legorooj requested changes
Just one _little_ thing: can you please fix the following filename:
```diff
+ _recursion_too_deep_message.py
- _recursion_to_deep_message.py
```

2020-09-13 18:00 UTC, htgoebel commented
The tests for this case are inconsistently failing on Win-64 Py 3.7 and 3.8 only: The respective worker is crashing. But this does not happen if only running these tests, see https://ci.appveyor.com/project/htgoebel/pyinstaller/builds/35176564. Since I have not time for debugging CI platform annoyances, I'll just remove the tests. @Legorooj Maybe you want to keep them as a base for tests when moving to modulegraph2.

2020-09-17 06:12 UTC, Legorooj commented
@htgoebel I did some digging and it looks like this is an issue with pytest-xdist's memory handling. I've applied the same fix that SciPy did so we'll merge if that works, and if not, keep digging.

2020-10-11 17:15 UTC, htgoebel commented
Since the pinning pytest-xdist did not help, I'm going to remove these test.

2020-10-11 17:18 UTC, htgoebel commented
Or better: I'm xfailing them for Wondoze.

2020-10-12 06:46 UTC, Legorooj approved these changes

2020-10-12 07:20 UTC, Legorooj requested changes

2020-10-12 07:20 UTC, Legorooj commented on tests/unit/test_recursion_limit.py
> +        pyi_main.run(pyi_args, PYI_CONFIG)
This clause isn't catching the RecursionError for some reason...

2020-10-18 19:41 UTC, merged