Add pathlib code to directories.py sample
pyinstaller/pyinstaller pull request #5192
Opened 2020-09-22 03:16 UTC by JustAShoeMaker

Add pathlib code to directories.py sample script equivalent to `os.path.dirname(os.path.abspath(__file__)) `  and provide explicit comparison/equality to it.

2020-09-22 04:34 UTC, Legorooj requested changes

2020-09-22 04:34 UTC, Legorooj commented on doc/runtime-information.rst
> +	print( 'PurePath(Path(__file__).absolute()).parent is ', PurePath(Path(__file__).absolute()).parent)
Why `PurePath` and not `Path`? The code should work as `Path(__file__).absolute().parent`.

2020-09-25 02:57 UTC, JustAShoeMaker commented on doc/runtime-information.rst
> +	print( 'PurePath(Path(__file__).absolute()).parent is ', PurePath(Path(__file__).absolute()).parent)
```suggestion
	print( 'Path(Path(__file__).absolute()).parent is ', Path(Path(__file__).absolute()).parent)
```

2020-09-25 02:57 UTC, JustAShoeMaker commented on doc/runtime-information.rst
> +	print( 'PurePath(Path(__file__).absolute()).parent is ', PurePath(Path(__file__).absolute()).parent)
Dont really recall now.

2020-09-27 11:40 UTC, Legorooj commented
After considering, I've decided to reject this change. I've put this on the todo list of things when this page of the docs gets an overhaul.

2020-09-27 11:40 UTC, closed without merging