Add a warning in the docs that the -u option does not work on Windows.
pyinstaller/pyinstaller pull request #5211
Opened 2020-10-01 10:34 UTC by bene64

The relevant issue https://github.com/pyinstaller/pyinstaller/issues/1441 which will maybe provide a fix in the future is linked.

2020-10-01 20:45 UTC, bwoodsend requested changes
Could you add the prefix `Doc:` to the top of the commit message? Then I think we should be OK to merge.

2020-10-02 04:21 UTC, bene64 commented
@bwoodsend I changed the commit message like requested.

2020-10-02 07:42 UTC, bwoodsend approved these changes

2020-10-02 07:50 UTC, Legorooj approved these changes

2020-10-02 07:51 UTC, merged