Avoid segfault when temp path is missing
pyinstaller/pyinstaller pull request #5255
Opened 2020-10-15 16:20 UTC by dcgloe

If the temp path is removed during application runtime (by a /tmp
cleaning script for example), the application will segfault on exit due
to calling readdir on a NULL pointer. Fix this issue by returning
immediately if the opendir fails.

2020-10-16 09:13 UTC, rokm approved these changes

2020-10-17 04:00 UTC, Legorooj requested changes
Can we please have a changelog entry?

2020-10-18 14:01 UTC, htgoebel requested changes
Beside the missing changeog entry: LGTM

2020-10-18 19:08 UTC, dcgloe commented
I've added a changelog entry, hopefully I did it right.

2020-10-19 05:42 UTC, Legorooj approved these changes
Thanks for this!

2020-10-19 05:42 UTC, merged