Fix build fail on cygwin.
pyinstaller/pyinstaller pull request #5466
Opened 2021-01-12 02:10 UTC by memo-off

[https://github.com/pyinstaller/pyinstaller/pull/3930#issue-238898175](url)

2021-01-12 09:23 UTC, htgoebel requested changes

2021-01-12 09:23 UTC, htgoebel commented on PyInstaller/depend/bindepend.py
> +            if is_cygwin and lib.lower().find('/cygdrive/c/windows/system') == 0:
Please use `.startswith`

2021-01-12 09:23 UTC, htgoebel commented on bootloader/wscript
> +    'cygwin': platform.system(),
What about SYSTEM_TO_BUILDOS?

2021-03-07 17:10 UTC, rokm approved these changes
Looks good to me. The changes indeed allow bootloader to be built under cygwin and also fix subsequent errors one gets when freezing a simple application.

And as the changes in flow affect only cygwin-related codepaths (i.e., under `is_cygwin` flag), I don't expect there to be any side effects, either.

2021-03-07 17:13 UTC, merged