Use public get_data_path for matplotlib hook
pyinstaller/pyinstaller pull request #5568
Opened 2021-02-19 11:59 UTC by richardsheridan

Fixes #5567. The bigger question is if this breaks earlier versions of matplotlib and how to deal with that if so.

2021-02-19 17:16 UTC, bwoodsend commented
Well our CI/CD is using matplotlib 3.2.2 and that hasn't broken so that's a good start. To be honest, I'm unaware of any reason why we can't just use the generic `collect_data_files("matplotlib")` that we normally use.

2021-02-19 17:17 UTC, bwoodsend requested changes
This needs a [news entry](https://pyinstaller.readthedocs.io/en/stable/development/changelog-entries.html).

Also can you spruce up the commit message? We've got quite a specific format going. Try `git log`-ing to get the idea.

2021-02-19 17:42 UTC, richardsheridan commented
> This needs a [news entry](https://pyinstaller.readthedocs.io/en/stable/development/changelog-entries.html).

on it

> Also can you spruce up the commit message? We've got quite a specific format going. Try `git log`-ing to get the idea.

Certainly, I noticed that just after I made the PR. 🤦 I'll do a force push after the appveyor build passes.

2021-02-20 14:56 UTC, bwoodsend commented
... and I can confirm that this still work on matplotlib 2.2.2 which is several years ago.

2021-02-20 14:56 UTC, bwoodsend approved these changes

2021-02-24 19:40 UTC, merged

2021-02-24 19:40 UTC, bwoodsend commented
Thanks @richardsheridan.