Add support for pkgutil.iter_modules
pyinstaller/pyinstaller pull request #5959
Opened 2021-06-30 09:37 UTC by rokm

TBA

2021-07-01 10:00 UTC, rokm commented
The initial plan for this was to implement support for `iter_modules` in our `FrozenImporter`. However, it turns out that `pkgutil` does not even consider it when resolving importers, because `pkgutil.get_importer` looks only for importers that are in `sys.path_hooks` (i.e., [path entry finders](https://docs.python.org/3/glossary.html#term-path-entry-finder)), whereas `FrozenImporter` is registered on `sys.meta_path` ([as meta path finder](https://docs.python.org/3/glossary.html#term-meta-path-finder)).

While it is possible to create a factory/finder for `sys.path_hooks`, this would mean that `FrozenImporter` becomes responsible for both PYZ-embedded resources and the on-filesystem resources (binary extensions, or .pyc modules in `noarchive` build). This seems rather excessive, and introduces additional complications (such as requiring `os.path` and/or `pathlib`).

All in all, it seems easier and cleaner to monkey-patch `pkgutil.iter_modules` to extend the results of original implementation (which lists on-filesystem resources discovered by python's `FileFinder`) with PYZ-embedded entries from `FrozenImporter`'s TOC.

2021-07-08 08:36 UTC, Legorooj approved these changes
Looks good.

2021-07-08 09:00 UTC, bwoodsend requested changes

2021-07-08 09:51 UTC, rokm commented on news/1905.feature.rst
> +Implement support for ``pkgutil.iter_modules``.
Argh, not again. Sorry, this will apparently take some time getting used to...

2021-07-08 09:52 UTC, rokm commented on PyInstaller/hooks/rthooks/pyi_rth_pkgutil.py
> +        pkg_prefix = pkg_prefix.replace(os.path.sep, '.')
Hmm, normally you'd pass it `package.__path__`, but yes, the path is user supplied and could be anything... Added an `os.path.normpath` to reduce the number of failure modes.

2021-07-11 08:37 UTC, merged