building: Add exclude_system_libraries method
pyinstaller/pyinstaller pull request #6022
Opened 2021-07-16 22:48 UTC by DrDaveD

This implements the feature requested in issue #2732.  It adds a
method in the Analysis class called exclude_system_libraries
that excludes all but python system libraries by default, and
accepts a list of exceptions that are file wildcards of libraries
to continue to including.

2021-07-16 22:48 UTC, DrDaveD commented
This replaces #6016.

2021-07-16 23:34 UTC, bwoodsend requested changes

2021-07-16 23:34 UTC, bwoodsend commented on PyInstaller/building/build_main.py
> +        self.binaries = [i for i in self.binaries if _include_binary(i, list_of_exceptions)]
Same feedback [as before](https://github.com/pyinstaller/pyinstaller/pull/6016#discussion_r670641757). Put unit tests in tests/unit/test_building_utils.py.

2021-07-17 09:47 UTC, rokm commented
The `site-packages` directories (as returned by `PyInstaller.compat.getsitepackages()`, for example) need to be exempted from exclusion. Otherwise, the function will filter out binaries coming from python packages when the user is either not using a virtual environment or is using a virtual environment with `--system-site-packages` enabled.

2021-07-19 13:48 UTC, DrDaveD commented
> The `site-packages` directories (as returned by `PyInstaller.compat.getsitepackages()`, for example) need to be exempted from exclusion. Otherwise, the function will filter out binaries coming from python packages when the user is either not using a virtual environment or is using a virtual environment with `--system-site-packages` enabled.

The `*python*` expression ought to cover that, correct?

2021-07-19 13:55 UTC, rokm commented
> > The `site-packages` directories (as returned by `PyInstaller.compat.getsitepackages()`, for example) need to be exempted from exclusion. Otherwise, the function will filter out binaries coming from python packages when the user is either not using a virtual environment or is using a virtual environment with `--system-site-packages` enabled.
> 
> The `*python*` expression ought to cover that, correct?

Yeah, you're right.

2021-07-19 13:56 UTC, rokm commented
> > > The `site-packages` directories (as returned by `PyInstaller.compat.getsitepackages()`, for example) need to be exempted from exclusion. Otherwise, the function will filter out binaries coming from python packages when the user is either not using a virtual environment or is using a virtual environment with `--system-site-packages` enabled.
> > 
> > 
> > The `*python*` expression ought to cover that, correct?
> 
> Yeah, you're right.

Actually, I don't think so, because that's matching destination path, not the source one.

2021-07-19 14:22 UTC, bwoodsend commented
As @rokm says, the source file `/path/to/python/lib/python3.9/site-packages/numpy.libs/libopenblasp-r0-5bebc122.3.13.dev.so` would have dest path `numpy.libs/libopenblasp-r0-5bebc122.3.13.dev.so` which doesn't have `python` in it.

Also, I'd have thought that at least some corner of Gtk would have `python` in a filename somewhere.

2021-07-19 14:29 UTC, DrDaveD commented
> > > > The `site-packages` directories (as returned by `PyInstaller.compat.getsitepackages()`, for example) need to be exempted from exclusion. Otherwise, the function will filter out binaries coming from python packages when the user is either not using a virtual environment or is using a virtual environment with `--system-site-packages` enabled.
> > > 
> > > 
> > > The `*python*` expression ought to cover that, correct?
> > 
> > 
> > Yeah, you're right.
> 
> Actually, I don't think so, because that's matching destination path, not the source one

Good point, I'll change that to match on the src.

2021-07-19 14:31 UTC, DrDaveD commented
> As @rokm says, the source file `/path/to/python/lib/python3.9/site-packages/numpy.libs/libopenblasp-r0-5bebc122.3.13.dev.so` would have dest path `numpy.libs/libopenblasp-r0-5bebc122.3.13.dev.so` which doesn't have `python` in it.
> 
> Also, I'd have thought that at least some corner of Gtk would have `python` in a filename somewhere.

This function is only excluding libraries coming from paths starting with `/lib` or `/usr/lib` so those coming from `/path/to` won't be considered.

2021-07-19 18:06 UTC, DrDaveD commented
Ok, it is updated including a unit test.

2021-07-19 19:56 UTC, bwoodsend commented
Yeah that's more like it.

2021-07-19 22:39 UTC, DrDaveD commented
Updated with changes for lint errors.

2021-07-20 10:22 UTC, bwoodsend requested changes

2021-07-20 10:23 UTC, bwoodsend commented
Now to try and find a sensible place to put it in the docs...

2021-07-20 10:58 UTC, rokm commented
> Now to try and find a sensible place to put it in the docs...

How about creating a short sub-section "Excluding system libraries (linux)" under "Using Spec Files"? And then reference that in the news fragment.

2021-07-20 12:27 UTC, bwoodsend commented
Sounds good to me.

2021-07-20 16:47 UTC, DrDaveD commented
The comment on the utils.py function was updated.

2021-07-20 18:24 UTC, bwoodsend requested changes
Looks good. Can we have a new *Linux Specific Options* section after [the macOS options in the spec file docs](https://github.com/pyinstaller/pyinstaller/blob/48430266d23567d1a325b37d64efd32541ca1bce/doc/spec-files.rst#spec-file-options-for-a-macosx-bundle) with a couple of sentences and a code example for how to use this. 

Then write a [news entry](https://pyinstaller.readthedocs.io/en/stable/development/changelog-entries.html) which includes a cross reference to that new section (use ``:ref:`Name of New Section` ``).

2021-07-20 19:21 UTC, rokm commented
> Actually, we don't currently enforce that this is Linux only anywhere. How do we want to handle if this method gets called on non-Linux?

It should already be effectively no-op elsewhere, with possible exception of `cygwin`.

2021-07-20 19:36 UTC, rokm commented
I think brew stuff goes into `/usr/local/Cellar`, and there's a site-packages at `/usr/local/lib/python3.9/site-packages`.

But whatever is in `/usr/lib` is explicitly ignored due to [this](https://github.com/pyinstaller/pyinstaller/blob/f5585e9c9602081a1b865e3c370c56846676270c/PyInstaller/depend/dylib.py#L226) and [this](https://github.com/ronaldoussoren/macholib/blob/3d7be0dc68be6bd53c96a3f35ecd4502589a24fb/macholib/util.py#L175-L187).

2021-07-21 17:50 UTC, DrDaveD commented
Added section to spec-files and added news entry.  I used "POSIX" instead of "Linux" because it is more general than Linux.

2021-07-21 18:00 UTC, bwoodsend requested changes

2021-07-21 18:40 UTC, DrDaveD commented on doc/spec-files.rst
> +and anything containing "krb" use this:
Oops.  Fixed with another force-push.

2021-07-21 19:45 UTC, bwoodsend approved these changes

2021-07-21 20:11 UTC, rokm approved these changes

2021-07-21 22:42 UTC, merged