Sort out argv emulation for macOS app bundles
pyinstaller/pyinstaller pull request #6089
Opened 2021-08-03 11:21 UTC by rokm

TBA

2021-08-03 20:34 UTC, rokm commented
Alright, marking this ready for review.

2021-08-03 23:03 UTC, bwoodsend commented
Ughh, this is way over my head. All I can suggest is that it would be nice to see some hello world code examples of receiving an event for some of the permutations listed in b1046922be1eb3b7e4cc1798390fd83fb74fa0bd. And there's a few ``` ``--argv-emulation`` ```s which could be cross references. Other than that, I'll have to take CI's word for it that this works...

2021-08-04 19:27 UTC, rokm commented
I've added cross-references for those `--argv-emulation` occurrences.

I need to think about the event handling examples, because this is not quite hello-world-level functionality (it depends on the UI toolkit, plus you need to register file extensions/URL schemas in the .spec file). I suppose I could repurpose my tkinter- and PySide2-based event loggers that didn't make it into the automated test into exemplar GUI loggers for open doc/url events instead...

2021-08-04 23:45 UTC, bwoodsend commented
If I understand [this](https://github.com/pyinstaller/pyinstaller/pull/6089/commits/71dbaead84ddb393905ce12b933cf2a3e8c63155#diff-ed2ef29371b4d95c70034a5aa21c4cc75e68b3ce5740ef6ee973f171e916d583R316-R326) correctly, with `argv_emulation` enabled, an application only has to read `sys.argv` and it will be launched to open files of an associated type? That option doesn't sound like more than a few lines to demonstrate? As for the other stuff, maybe leave it then. Is this event handling possible in regular unfrozen Python? i.e. Will there be other sources of examples in the various GUI toolkits' docs?

2021-08-05 13:28 UTC, rokm commented
> That option doesn't sound like more than a few lines to demonstrate?

Sure, but the "code" part itself is trivial (i.e., read ``sys.argv``). It's everything else (like setting up associations in .spec file) that is a hassle here... But I think I came up with decent example for an application using argv emu.

> Is this event handling possible in regular unfrozen Python?

I'm not sure if it is. I mean, it is probably possible to set up a bundle with bash launcher script that runs a python script in system-wide python interpreter, but I have no idea how practical and wide-spread it is.

>  i.e. Will there be other sources of examples in the various GUI toolkits' docs?

There is some documentation available for [Tcl/Tk](https://www.tcl.tk/man/tcl8.5/TkCmd/tk_mac.html) and [Qt](https://doc.qt.io/qt-5/qfileopenevent.html), but I think it again tells only a part of the story. 

I suppose for people not very familiar with the topic, it's actually indeed best to have a complete example.

2021-08-05 22:13 UTC, bwoodsend requested changes
Whoah that's more than I expected. I don't think PyInstaller has ever seen that much documentation! There's a couple of missing `the`s but other than that it looks great.

2021-08-06 09:30 UTC, rokm commented on doc/feature-notes.rst
> +utility, to be evoked from terminal as follows::
Indeed.

2021-08-06 12:38 UTC, bwoodsend approved these changes

2021-08-19 09:35 UTC, merged

2021-08-19 14:31 UTC, jamesbcd commented
This is a really well-thought-out design, and the documentation is extraordinarily good. Thanks so much for developing it.