The motivation here is to enable a "highly-optimized platform security
pyinstaller/pyinstaller pull request #6136
Opened 2021-08-18 14:48 UTC by AdrianIssott

The motivation here is to enable a "highly-optimized platform security
feature that was created to combat memory corruption vulnerabilities".

Note that "CFG enabled code works fine on "CFG-Unaware" versions 
of Windows and is therefore fully compatible with them"

Quotes from
https://docs.microsoft.com/en-us/windows/win32/secbp/control-flow-guard

2021-08-18 15:42 UTC, bwoodsend commented
I thought we already had this because [we would have had to disable it to support lief](https://github.com/pyinstaller/pyinstaller/pull/5996/files#r669036250)? Or is that for some other OS/compiler pair?

2021-08-18 15:45 UTC, rokm commented
> I thought we already had this because [we would have had to disable it to support lief](https://github.com/pyinstaller/pyinstaller/pull/5996/files#r669036250)? Or is that for some other OS/compiler pair?

Those were gcc-made ELF binaries on linux.

2021-08-18 15:49 UTC, AdrianIssott commented
One additional thing to note: "This feature is available in Microsoft Visual Studio 2015" which I believe means this change, as it stands, would fail to compile with an earlier Visual Studio. I'm unsure if that is consider a problem or not ...

2021-08-18 15:51 UTC, bwoodsend requested changes
OK, this sounds sensible then. This just needs a [news entry](https://pyinstaller.readthedocs.io/en/stable/development/changelog-entries.html) then I'm happy.

2021-08-18 15:53 UTC, rokm commented
> One additional thing to note: "This feature is available in Microsoft Visual Studio 2015" which I believe means this change, as it stands, would fail to compile with an earlier Visual Studio. I'm unsure if that is consider a problem or not ...

That's not a problem, as we do not support VS versions earlier than 2015.

2021-08-18 15:55 UTC, bwoodsend commented
> One additional thing to note: "This feature is available in Microsoft Visual Studio 2015" which I believe means this change, as it stands, would fail to compile with an earlier Visual Studio. I'm unsure if that is consider a problem or not ...

Ahh, that's more complicated then. MSVC 14 is still relatively normal. I guess some kind of version check would be needed. Or failing that, another one of those `ctx.check_cc()` calls...

2021-08-18 15:55 UTC, bwoodsend commented
Oh, ignore me then. I didn't realise we'd dropped support already.

2021-08-18 15:58 UTC, rokm commented
> Oh, ignore me then. I didn't realise we'd dropped support already.

Yeah, since #5321, VS 2015 is the minimum. But that *is* 14.0 (whereas 2013 was 12.0).

2021-08-18 17:28 UTC, bwoodsend commented on news/6136.build.rst
> +(Windows) Enable Control Flow Guard for the Windows bootloader
```suggestion
(Windows) Enable `Control Flow Guard <https://docs.microsoft.com/en-us/windows/win32/secbp/control-flow-guard>`_ for the Windows bootloader
```

2021-08-18 17:30 UTC, rokm commented on news/6136.build.rst
> +(Windows) Enable Control Flow Guard for the Windows bootloader
And add a period (.) at the end.

2021-08-18 17:31 UTC, bwoodsend approved these changes

2021-08-18 17:32 UTC, bwoodsend commented
@rokm Merge this is you're happy with it.

2021-08-18 17:42 UTC, rokm approved these changes

2021-08-18 17:42 UTC, merged

2021-08-18 17:43 UTC, rokm commented
Thanks @AdrianIssott !

2021-08-19 08:37 UTC, AdrianIssott commented
Many thanks @rokm and @bwoodsend for your swift responses