Fix some errors on non x86 platforms.
pyinstaller/pyinstaller pull request #6306
Opened 2021-10-19 03:10 UTC by wangling12

2021-10-19 09:24 UTC, bwoodsend requested changes

2021-10-19 09:24 UTC, bwoodsend commented on PyInstaller/_shared_with_waf.py
> +    if platform.machine() == "sw_64" or platform.machine() == "loongarch64":
Why put it here and block cross compilation? What's the output of `gcc -dumpmachine` on loongarch64?

2021-10-19 09:24 UTC, bwoodsend commented on PyInstaller/_shared_with_waf.py
> +    else:
Surely you mean?
```suggestion
    if machine in ("s390x",):
```
Otherwise, you'd make `machine` the default which we definitely don't want or waf will be unable to put the bootloaders where PyInstaller expects to find them.

2021-10-19 09:24 UTC, bwoodsend commented on PyInstaller/_shared_with_waf.py
>      # See the corresponding tests in tests/unit/test_compat.py for examples.
Can you update [the corresponding test's parametrisation](https://github.com/pyinstaller/pyinstaller/blob/d53be0c8c9c961952ea1a08646d29fc920f12537/tests/unit/test_compat.py#L29-L48) too so that a) we know that it works and b) future PyInstaller developers know what that function is likely to recieve? This should include both Python's `platform.machine()` and `gcc -dumpmachine` for each architecture.

2021-10-20 07:30 UTC, wangling12 commented on PyInstaller/_shared_with_waf.py
> +    if platform.machine() == "sw_64" or platform.machine() == "loongarch64":
https://github.com/pyinstaller/pyinstaller/blob/d53be0c8c9c961952ea1a08646d29fc920f12537/bootloader/wscript#L87
In this call, `ctx.env.DEST_CPU` is null, and `loongarch64` can be obtained by using `platform.machine()`, so I put it here.

```shell
$ gcc -dumpmachine
loongarch64-linux-gnu
```

2021-10-20 07:40 UTC, wangling12 commented on PyInstaller/_shared_with_waf.py
> +    else:
Maybe for these cases that do not need to be processed, we only need to return `machine` and do not need to list a long list?

2021-10-20 07:58 UTC, wangling12 commented on PyInstaller/_shared_with_waf.py
>      # See the corresponding tests in tests/unit/test_compat.py for examples.
I hope my push meets expectations.

2021-10-20 10:15 UTC, bwoodsend commented on PyInstaller/_shared_with_waf.py
> +    else:
Yes, the cases which we know have no aliases (or rather `platform.machine() == ctx.env.DEST_CPU`) can safely be returned as-is (by returning `machine`) but for unknown architectures that we've never seen before, it's unlikely that `platform.machine()` and `ctx.env.DEST_CPU` agree with each other so we must normalise to a fixed value (`"unknown"`).

2021-10-20 10:18 UTC, bwoodsend commented on PyInstaller/_shared_with_waf.py
> +    if platform.machine() == "sw_64" or platform.machine() == "loongarch64":
Damn, waf isn't recognising it. No cross compiling it is then...

2021-10-21 10:44 UTC, bwoodsend commented on tests/unit/test_compat.py
> +        ("sw_64", "sw_64"),
You'll have to remove these two. We can't test the ones that don't support cross compile.

2021-10-22 13:44 UTC, bwoodsend commented
Looks good. I'm able to reproduce the issue with MIPS and verify that this PR resolves it. I'll have to take your word for it for loongarch64 because it seems that not even qemu supports it. Can you add a [news entry](https://pyinstaller.readthedocs.io/en/stable/development/changelog-entries.html) (something like *Fix compatibility with with MIPS and loongarch64 architectures.*) then I'll merge this.

2021-10-25 02:42 UTC, wangling12 commented
I rebase the comments to make them look more concise.
QEMU's support for loongarch64 should be [in progress](https://patchew.org/QEMU/1630586467-22463-1-git-send-email-gaosong@loongson.cn/). 

Thank you for your patient review.

2021-10-25 13:40 UTC, merged

2021-10-25 13:44 UTC, bwoodsend commented
Thanks @wangling12!